services:
  db:
    image: postgres:18
    environment:
      POSTGRES_DB: ${DB_NAME:-university}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-password}
    volumes:
      - pgdata:/var/lib/postgresql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
#    ports:
#      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: ./app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME:-university}
      DB_USER: ${DB_USER:-postgres}
      DB_PASS: ${DB_PASS:-password}
      SECRET_KEY: ${SECRET_KEY:-change_me}
      ADMIN_BOOTSTRAP_ENABLED: ${ADMIN_BOOTSTRAP_ENABLED:-false}
      ADMIN_BOOTSTRAP_LOGIN: ${ADMIN_BOOTSTRAP_LOGIN:-admin}
      ADMIN_BOOTSTRAP_PASSWORD: ${ADMIN_BOOTSTRAP_PASSWORD:-}

  nginx:
    build: ./nginx
    depends_on:
      - web
    ports:
      - "8084:443"
      - "8083:80"
    environment:
      SSL_CN: ${SSL_CN:-localhost}
    volumes:
      - nginx_certs:/etc/nginx/certs

volumes:
  pgdata:
  nginx_certs:
